export { PortReference } from './port-opener/port-reference'
export { serialPortOpenner as serialPortOpenner_PC } from './port-opener/port-opener-PC'
export { SerialPortOpener } from './port-opener/port-opener-core'
export { syncTransactioner } from './sync-transactioner/sync-transactioner'
export { Byte, Bytes } from './data-models/bytes'
export { Datalinker, ResultError, ReceptionHandlerResult, ResultProcessing, ResultSucessful } from './data-models/datalinker-sync'